import Layout from '@/components/Layout/Layout'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { Provider } from 'react-redux'
import store from '../store/index'
import '../styles/global.scss'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { MyLoader } from '@/components/UI/loader'

export default function App({ Component, pageProps }: AppProps) {
  const [isLoading, setLoading] = useState(false);
  const router = useRouter();

  useEffect(() => {
    const handleStart = (url: string) => (url !== router.asPath) && setLoading(true);
    const handleComplete = (url: string) => (url === router.asPath) && setLoading(false);

    router.events.on('routeChangeStart', handleStart)
    router.events.on('routeChangeComplete', handleComplete)
    router.events.on('routeChangeError', handleComplete)

    return () => {
        router.events.off('routeChangeStart', handleStart)
        router.events.off('routeChangeComplete', handleComplete)
        router.events.off('routeChangeError', handleComplete)
    }
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> 
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@100&family=Lato:wght@100;300;400;700&display=swap" rel="stylesheet" /> 
      </Head>
      <Provider store={store}>
        <Layout>
          {
            isLoading
            ? <MyLoader />
            : <Component {...pageProps} />
          }
        </Layout>
      </Provider>
    </>
  )
}
